"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.megaPokemonNames = void 0;
exports.megaPokemonNames = [
    'venusaur',
    'charizard',
    'charizard',
    'blastoise',
    'beedrill',
    'ampharos',
    'steelix',
    'scizor',
    'heracross',
    'houndoom',
    'tyranitar',
    'sceptile',
    'blaziken',
    'swampert',
    'gardevoir',
    'sableye',
    'mawile',
    'aggron',
    'medicham',
    'manectric',
    'sharpedo',
    'camerupt',
    'altaria',
    'banette',
    'absol',
    'glalie',
    'salamence',
    'metagross',
    'lopunny',
    'garchomp',
    'lucario',
    'abomasnow',
    'gallade',
    'audino',
    'diancie',
    'pidgeot',
    'slowbro',
    'gengar',
    'alakazam',
];
