const b = {
  evolutionChain: [
    {
      is_baby: false,
      species: { url: 'https://pokeapi.co/api/v2/pokemon-species/25/', name: 'pikachu' },
      evolves_to: [
        {
          is_baby: false,
          species: { url: 'https://pokeapi.co/api/v2/pokemon-species/26/', name: 'raichu' },
          evolves_to: [],
          evolution_details: [
            {
              item: { url: 'https://pokeapi.co/api/v2/item/83/', name: 'thunder-stone' },
              gender: null,
              trigger: { url: 'https://pokeapi.co/api/v2/evolution-trigger/3/', name: 'use-item' },
              location: null,
              held_item: null,
              min_level: null,
              known_move: null,
              min_beauty: null,
              party_type: null,
              time_of_day: '',
              min_affection: null,
              min_happiness: null,
              party_species: null,
              trade_species: null,
              known_move_type: null,
              turn_upside_down: false,
              needs_overworld_rain: false,
              relative_physical_stats: null,
            },
          ],
        },
      ],
      evolution_details: [
        {
          item: null,
          gender: null,
          trigger: { url: 'https://pokeapi.co/api/v2/evolution-trigger/1/', name: 'level-up' },
          location: null,
          held_item: null,
          min_level: null,
          known_move: null,
          min_beauty: null,
          party_type: null,
          time_of_day: '',
          min_affection: null,
          min_happiness: 160,
          party_species: null,
          trade_species: null,
          known_move_type: null,
          turn_upside_down: false,
          needs_overworld_rain: false,
          relative_physical_stats: null,
        },
      ],
    },
  ],
  isFirstEvolution: false,
}
