"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Type = exports.Tournament = exports.Talent = exports.Skill = exports.Session = exports.RoomUpgrades = exports.RanchSlot = exports.Ranch = exports.RaidRoom = exports.RaidPokemon = exports.Raid = exports.Quest = exports.Pokemon = exports.PokeTeam = exports.Player = exports.Message = exports.MarketOffer = exports.Item = exports.InvasionSession = exports.HeldItem = exports.GymPokemon = exports.GymLeader = exports.GameRoom = exports.EBerryTreePhases = exports.EBerryNames = exports.BerryTree = exports.BaseRoomUpgrades = exports.BasePokemon = exports.BaseItem = exports.Badge = void 0;
var client_1 = require("@prisma/client");
Object.defineProperty(exports, "Badge", { enumerable: true, get: function () { return client_1.Badge; } });
Object.defineProperty(exports, "BaseItem", { enumerable: true, get: function () { return client_1.BaseItem; } });
Object.defineProperty(exports, "BasePokemon", { enumerable: true, get: function () { return client_1.BasePokemon; } });
Object.defineProperty(exports, "BaseRoomUpgrades", { enumerable: true, get: function () { return client_1.BaseRoomUpgrades; } });
Object.defineProperty(exports, "BerryTree", { enumerable: true, get: function () { return client_1.BerryTree; } });
Object.defineProperty(exports, "EBerryNames", { enumerable: true, get: function () { return client_1.EBerryNames; } });
Object.defineProperty(exports, "EBerryTreePhases", { enumerable: true, get: function () { return client_1.EBerryTreePhases; } });
Object.defineProperty(exports, "GameRoom", { enumerable: true, get: function () { return client_1.GameRoom; } });
Object.defineProperty(exports, "GymLeader", { enumerable: true, get: function () { return client_1.GymLeader; } });
Object.defineProperty(exports, "GymPokemon", { enumerable: true, get: function () { return client_1.GymPokemon; } });
Object.defineProperty(exports, "HeldItem", { enumerable: true, get: function () { return client_1.HeldItem; } });
Object.defineProperty(exports, "InvasionSession", { enumerable: true, get: function () { return client_1.InvasionSession; } });
Object.defineProperty(exports, "Item", { enumerable: true, get: function () { return client_1.Item; } });
Object.defineProperty(exports, "MarketOffer", { enumerable: true, get: function () { return client_1.MarketOffer; } });
Object.defineProperty(exports, "Message", { enumerable: true, get: function () { return client_1.Message; } });
Object.defineProperty(exports, "Player", { enumerable: true, get: function () { return client_1.Player; } });
Object.defineProperty(exports, "PokeTeam", { enumerable: true, get: function () { return client_1.PokeTeam; } });
Object.defineProperty(exports, "Pokemon", { enumerable: true, get: function () { return client_1.Pokemon; } });
Object.defineProperty(exports, "Quest", { enumerable: true, get: function () { return client_1.Quest; } });
Object.defineProperty(exports, "Raid", { enumerable: true, get: function () { return client_1.Raid; } });
Object.defineProperty(exports, "RaidPokemon", { enumerable: true, get: function () { return client_1.RaidPokemon; } });
Object.defineProperty(exports, "RaidRoom", { enumerable: true, get: function () { return client_1.RaidRoom; } });
Object.defineProperty(exports, "Ranch", { enumerable: true, get: function () { return client_1.Ranch; } });
Object.defineProperty(exports, "RanchSlot", { enumerable: true, get: function () { return client_1.RanchSlot; } });
Object.defineProperty(exports, "RoomUpgrades", { enumerable: true, get: function () { return client_1.RoomUpgrades; } });
Object.defineProperty(exports, "Session", { enumerable: true, get: function () { return client_1.Session; } });
Object.defineProperty(exports, "Skill", { enumerable: true, get: function () { return client_1.Skill; } });
Object.defineProperty(exports, "Talent", { enumerable: true, get: function () { return client_1.Talent; } });
Object.defineProperty(exports, "Tournament", { enumerable: true, get: function () { return client_1.Tournament; } });
Object.defineProperty(exports, "Type", { enumerable: true, get: function () { return client_1.Type; } });
