export const plateTypeMap: Map<string, string> = new Map<string, string>([
  ['flame plate', 'fire'],
  ['sky plate', 'flying'],
  ['splash plate', 'water'],
  ['zap plate', 'electric'],
  ['meadow plate', 'grass'],
  ['icicle plate', 'ice'],
  ['fist plate', 'fighting'],
  ['toxic plate', 'poison'],
  ['earth plate', 'ground'],
  ['mind plate', 'psychic'],
  ['insect plate', 'bug'],
  ['stone plate', 'rock'],
  ['spooky plate', 'ghost'],
  ['draco plate', 'dragon'],
  ['dread plate', 'dark'],
  ['iron plate', 'steel'],
  ['pixie plate', 'fairy'],
])
